import type { Metadata } from "next";
import "./globals.css";
import HeaderWrapper from "@/components/header-wrapper";
import HeroFooter from "@/components/footer";
import {
  bricolageGrotesque,
  interTight,
  inter,
  instrumentSerif,
} from "./fonts";
import ContactSection from "@/components/contact-section";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bricolageGrotesque.variable} ${interTight.variable} ${inter.variable} ${instrumentSerif.variable}`}
    >
      <body className="antialiased">
        <HeaderWrapper />
        {children}
        <ContactSection />
        <footer>
        <HeroFooter  />
        </footer>
      </body>
    </html>
  );
}
