import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import HeaderWrapper from "@/components/header-wrapper";
import HeroFooter from "@/components/footer";

const bricolage_Grotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
 

});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bricolage_Grotesque.variable} antialiased`}
      >
        <HeaderWrapper />
        {children}
        <footer>
        <HeroFooter backgroundUrl="/footer.avif" />
        </footer>
      </body>
    </html>
  );
}
